export const ORDER_INTENT_CAPTURE = 'CAPTURE';
export const ORDER_INTENT_AUTHORIZE = 'AUTHORIZE';

export const INVOICE_CANCELED = 'INVOICING.INVOICE.CANCELLED';
export const INVOICE_PAID = 'INVOICING.INVOICE.PAID';
export const ORDER_COMPLETED = 'CHECKOUT.ORDER.COMPLETED';
export const ORDER_APPROVED = 'CHECKOUT.ORDER.APPROVED';
export const PAYMENT_ORDER_CREATED = 'PAYMENT.ORDER.CREATED';
export const PAYMENT_ORDER_CANCELED = 'PAYMENT.ORDER.CANCELLED';
export const PAYMENT_CAPTURE_DENIED = 'PAYMENT.CAPTURE.DENIED';
export const PAYMENT_AUTHORIZATION_VOIDED = 'PAYMENT.AUTHORIZATION.VOIDED';
