export { default as Carousel } from './Carousel';
export * from './types';
export {
  DEFAULT_CAROUSEL_LIST,
  DEFAULT_CAROUSEL_WIDTH_IMAGE,
  DEFAULT_CAROUSEL_HEIGHT_IMAGE,
  DEFAULT_CAROUSEL_NAV_TYPE,
  DEFAULT_CAROUSEL_DIRECTION,
  DEFAULT_CAROUSEL_SHOW_NAVIGATE,
  DEFAULT_CAROUSEL_SHOW_PAGINATION,
  DEFAULT_CAROUSEL_AUTOPLAY,
  DEFAULT_CAROUSEL_SWIPE_GESTURES,
  DEFAULT_CAROUSEL_LOOP,
  DEFAULT_CAROUSEL_DELAY,
  DEFAULT_CAROUSEL_EFFECT,
} from './default-data';
